Mini2440 modify 3.15: modify touchscreen driver
There are some differeces.
1. rename s3c2410_ts.c to mini2440_ts.c
   because there was s3c2410_ts.c already.

2. configure
Device Drivers  --->
 Input device support  --->
  [*] Touchscreens  --->
   <*> Samsung S3C2410 touchscreen input driver

3.s3c2410_gpio_cfgpin -> s3c_gpio_cfgpin
.-------------------------------------------------------------------------------.
|42: error: implicit declaration of function 's3c2410_gpio_cfgpin'              |
'-------------------------------------------------------------------------------'

4.remove IRQF_SAMPLE_RANDOM
.-------------------------------------------------------------------------------.
|202: error: 'IRQF_SAMPLE_RANDOM' undeclared (first use in this function)       |
'-------------------------------------------------------------------------------'
IRQF_SAMPLE_RANDOM has been removed from the linux kernel.
Just remove this symbol and replace it with 0.
from: b4237003cff66084ebeb502412d9cee392e6f52f

5. BIT -> BIT_MASK; BIT_TO_LONGS -> BIT_WORD.
.-------------------------------------------------------------------------------.
|189: warning: left shift count >= width of type                                |
'-------------------------------------------------------------------------------'
referece s3c2410_ts.c of mainline.

6. TODO: reset include/uapi/linux/input.h
changed EV_VERSION to 0x010000 from 0x010001 just for old version tslib.
That's not a good way for userspace error to modify kernel source.
This is just a temp way.
.-------------------------------------------------------------------------------.
|selected device is not a touchscreen I understand                              |
'-------------------------------------------------------------------------------'